name: Sync Repositories on Push

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch of the development repo

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout first-repo
      uses: actions/checkout@v2
      with:
        repository: '2002lokesh/first-repo'  # Updated to your repository
        ref: main  # Default branch
        token: ${{ secrets.test }}  # Personal access token renamed to 'test'

    - name: Configure Git user
      run: |
        git config --global user.email "lokeshkcse314@gmail.com"
        git config --global user.name "2002lokesh"

    - name: Pull latest changes from first-repo repository
      run: |
        git pull origin main --rebase  # Pull and rebase to avoid conflicts

    - name: Push changes to first-repo repository
      run: |
        git push origin main  # Push to the main branch of your first-repo

    - name: Show recently committed folders and files
      run: |
        echo "Listing recently committed files and folders:"
        git log -1 --name-status --oneline
