name: Auto Pull Request

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  schedule:
    - cron: '0 * * * *'  # Scheduled to run every hour (UTC)

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Create Pull Request
        id: create_pr
        run: |
          git config --local user.email "lokeshkcse314@gmail.com"  # Set your email
          git config --local user.name "2002lokesh"  # Set your name
          
          # Check if there are any changes to commit
          if ! git diff --quiet; then
            git add .
            git commit -m "Automated Pull Request"
            git push origin main
            echo "Pull request created."
          else
            echo "No changes to commit."
          fi
