name: Sync to Second Repository

on:
  push:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first repo
        uses: actions/checkout@v2

      - name: Clone the second repository
        run: |
          # Clone the second repository into a temporary directory
          git clone https://github.com/2002lokesh/second-repo.git temp-repo
          
      - name: Copy files to second repo
        run: |
          # Copy all files from the first repo (current directory) to the cloned second repo directory
          cp -r ./* temp-repo/  # Copy files from first repo to temp-repo

      - name: Commit and push changes to the second repo
        run: |
          cd temp-repo
          # Set up git configuration
          git config user.name "2002lokesh"
          git config user.email "lokeshkcse314@gmail.com"
          # Add, commit, and push changes
          git add .
          git commit -m "Sync from first repo" || echo "No changes to commit"
          git push https://2002lokesh:${{ secrets.SECOND_REPO_TOKEN }}@github.com/2002lokesh/second-repo.git main
